services:
  # ==========================================
  # FASE 0: INFRAESTRUCTURA BASE (BITNAMI)
  # ==========================================
  zookeeper:
    # Usamos la imagen oficial de la librería de Docker (más compatible)
    image: zookeeper:3.9
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - iot-network

  # ==========================================
  # FASE 0: INFRAESTRUCTURA BASE (APACHE KAFKA OFICIAL)
  # ==========================================
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Configuración de KRaft (Sin Zookeeper)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - iot-network

  iot-postgres:
    image: postgres:15-alpine
    container_name: iot-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: industria40
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iot-network

  # ==========================================
  # FASE 1: GEMELO DIGITAL E INGESTA
  # ==========================================
  simulador-iot:
    build: ./simulador_iot
    container_name: simulador-iot
    depends_on:
      - kafka
      - iot-postgres
    networks:
      - iot-network

  # ==========================================
  # FASE 2: MOTOR DE DECISIÓN (IA + SPARK)
  # ==========================================
  iot-spark-app:
    build: ./procesamiento_spark
    container_name: iot-spark-app
    depends_on:
      - kafka
      - iot-postgres
    networks:
      - iot-network

  # ==========================================
  # FASE 3 & 4: API BACKEND Y DASHBOARD
  # ==========================================
  api-servicio:
    build: ./api_backend
    container_name: api-servicio
    ports:
      - "8000:8000"
    depends_on:
      - iot-postgres
    networks:
      - iot-network

  dashboard:
    build: ./dashboard_web
    container_name: dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api-servicio
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge

volumes:
  postgres_data:
