services:
  # ==========================================
  # FASE 0: INFRAESTRUCTURA BASE
  # ==========================================
  iot-postgres:
    image: postgres:15
    container_name: iot-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: industria40
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iot-network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - iot-network

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Industria40_Secure
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    networks:
      - iot-network

  nginx-proxy:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx_data:/data
      - ./nginx_letsencrypt:/etc/letsencrypt
    networks:
      - iot-network

  # ==========================================
  # FASE 1: SIMULADOR (EL CAOS)
  # ==========================================
  simulador-iot:
    build: ./simulador_iot
    container_name: simulador-iot
    restart: always
    networks:
      - iot-network

  # ==========================================
  # FASE 2: CEREBRO IA (SPARK)
  # ==========================================
  iot-spark-app:
    build: ./procesamiento_spark
    container_name: iot-spark-app
    restart: always
    networks:
      - iot-network

  # ==========================================
  # FASE 3: SERVICIOS WEB (API & DASHBOARD)
  # ==========================================
  api-servicio:
    build: ./api_backend
    container_name: api-servicio
    restart: always
    ports:
      - "8000:8000"
    networks:
      - iot-network

  dashboard:
    build: ./dashboard_web
    container_name: dashboard
    restart: always
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.enableCORS=false --server.enableXsrfProtection=false
    networks:
      - iot-network

  notificador-telegram:
    build: ./notificador
    container_name: notificador-telegram
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    networks:
      - iot-network
    depends_on:
      - api-servicio

networks:
  iot-network:
    driver: bridge
